# ###*
# # checks if Push notification and service workers are supported by your browser
# ###

isPushNotificationSupported = ->
  'serviceWorker' of navigator and 'PushManager' of window

# ###*
# # asks user consent to receive push notifications and returns the response of the user, one of granted, default, denied
# ###

initializePushNotifications = ->
    # request user grant to show notification
    Notification.requestPermission (result) ->
        console.log 'res', result
        result

# ###*
# # shows a notification
# ###

sendNotification = ->
  img = '/images/jason-leung-HM6TMmevbZQ-unsplash.jpg'
  text = 'Take a look at this brand new t-shirt!'
  title = 'New Product Available'
  options = 
    body: text
    icon: '/images/jason-leung-HM6TMmevbZQ-unsplash.jpg'
    vibrate: [
      200
      100
      200
    ]
    tag: 'new-product'
    image: img
    badge: 'https://spyna.it/icons/android-icon-192x192.png'
    actions: [ {
      action: 'Detail'
      title: 'View'
      icon: 'https://via.placeholder.com/128/ff0000'
    } ]
  navigator.serviceWorker.ready.then (serviceWorker) ->
    serviceWorker.showNotification title, options
    return
  return

# ###*
# # 
# ###

# registerServiceWorker = ->
#   navigator.serviceWorker.register('/sw.js').then (swRegistration) ->
#     #you can do something with the service wrker registration (swRegistration)
#     return
#   return

# # ---
# # generated by js2coffee 2.2.0
